version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: sakshidb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - ola_network

  springboot:
    build:
      context: .  # Use the current directory as the build context
    container_name: OI_service
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sakshi-oi-rds.crfeuztyzstf.us-west-2.rds.amazonaws.com:3306/sakshidb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Sakshisonje

networks:
  ola_network:
    driver: bridge
